version: 2.1
defaults: &defaults
  working_directory: ~/lumigo-node-log-shipper
  docker:
    - image: lumigo/ci:latest
      auth:
        username: lumigo
        password: $DOCKERHUB_PASSWORD

workflows:
  test-deploy:
    jobs:
    - test
    - deploy:
        requires:
        - test
        filters:
          branches:
            only: master

jobs:
  test:
    <<: *defaults
    steps:
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: export AWS_DEFAULT_REGION=us-west-2 && export USER=CICD && ./scripts/checks.sh
      - run: bash <(curl -s https://codecov.io/bash)

  deploy:
    <<: *defaults
    steps:
      - run: ./scripts/bd_to_prod.sh